// AUTO-GENERATED by scripts/gen_preset_mapper.py — do not edit manually
// Maps randomizer preset keys → settingsStore fields.

const _ENUM = {
  MAP_SETTING: ['dungeonMaps', {
    MAP_KEASY: 'start_with',
    MAP_STANDARD: 'own_dungeon',
    MAP_REGION: 'own_dungeon',
    MAP_KEYSANITY: 'anywhere',
  }],
  COMPASS_SETTING: ['dungeonCompasses', {
    COMPASS_KEASY: 'start_with',
    COMPASS_STANDARD: 'own_dungeon',
    COMPASS_REGION: 'own_dungeon',
    COMPASS_KEYSANITY: 'anywhere',
  }],
  SMALL_KEYS_SETTING: ['dungeonSmallKeys', {
    SMALL_KEASY: 'start_with',
    SMALL_KEYS_STANDARD: 'own_dungeon',
    SMALL_KEYS_REGION: 'own_dungeon',
    SMALL_KEYS_VANILLA: 'own_dungeon',
    SMALL_KEYSANITY: 'anywhere',
  }],
  BIG_KEYS_SETTING: ['dungeonBigKeys', {
    BIG_KEASY: 'start_with',
    BIG_KEYS_STANDARD: 'own_dungeon',
    BIG_KEYS_REGION: 'own_dungeon',
    BIG_KEYS_VANILLA: 'own_dungeon',
    BIG_KEYSANITY: 'anywhere',
  }],
  SHUFFLE_ELEMENTS: ['shuffleElements', {
    SHUFFLE_ELEMENTS_OFF: 'vanilla',
    SHUFFLE_ELEMENTS_VANILLA: 'vanilla',
    SHUFFLE_ELEMENTS_DUNGEON: 'dungeon_prize',
    SHUFFLE_ELEMENTS_DUNGEON_PRIZE: 'dungeon_prize',
    SHUFFLE_ELEMENTS_REGION: 'dungeon_prize',
    SHUFFLE_ELEMENTS_ON: 'anywhere',
  }],
  DHC_SETTING: ['dhcAccess', {
    NODHC: 'closed',
    NORMALDHC: 'pedestal',
    OPENDHC: 'open',
  }],
  GOLD_FUSION_SETTING: ['goldFusionAccess', {
    NO_GOLD_FUSIONS: 'closed',
    VANILLA_GOLD_FUSIONS: 'vanilla',
    COMBINED_GOLD_FUSIONS: 'combined',
    OPEN_GOLD_FUSIONS: 'open',
  }],
  RED_FUSION_SETTING: ['redFusionAccess', {
    NO_RED_FUSIONS: 'closed',
    VANILLA_RED_FUSIONS: 'vanilla',
    COMBINED_RED_FUSIONS: 'combined',
    OPEN_RED_FUSIONS: 'open',
  }],
  BLUE_FUSION_SETTING: ['blueFusionAccess', {
    NO_BLUE_FUSIONS: 'closed',
    VANILLA_BLUE_FUSIONS: 'vanilla',
    COMBINED_BLUE_FUSIONS: 'combined',
    OPEN_BLUE_FUSIONS: 'open',
  }],
  GREEN_FUSION_SETTING: ['greenFusionAccess', {
    NO_GREEN_FUSIONS: 'closed',
    VANILLA_GREEN_FUSIONS: 'vanilla',
    COMBINED_GREEN_FUSIONS: 'combined',
    OPEN_GREEN_FUSIONS: 'open',
  }],
  BIGGORON_SETTING: ['biggoron', {
    BIGGORON_OFF: 'disabled',
    BIGGORON_NORMAL: 'shield',
    BIGGORON_SHIELD: 'shield',
    BIGGORON_MIRROR: 'mirror_shield',
  }],
  BOMBWEAPON: ['weaponBomb', {
    NOBOMB: 0,
    YESBOMB: 1,
    BOSSBOMB: 2,
  }],
  BOWWEAPON: ['weaponBow', {
    NOBOW: false,
    YESBOW: true,
    BOSSBOW: true,
  }],
  GUSTWEAPON: ['weaponGust', {
    NOGUST: false,
    YESGUST: true,
  }],
  LAMPWEAPON: ['weaponLantern', {
    NOLAMP: false,
    YESLAMP: true,
  }],
}

const _BOOL = {
  CRENEL_CREST: 'windCrestCrenel',
  FALLS_CREST: 'windCrestFalls',
  CLOUD_CREST: 'windCrestClouds',
  TOWN_CREST: 'windCrestCastor',
  SHF_CREST: 'windCrestSouthField',
  MINISH_CREST: 'windCrestMinishWoods',
  RUPEEMANIA: 'rupeesanity',
  SPECIALPOTS: 'shufflePots',
  DIGGING: 'shuffleDigging',
  UNDERWATER: 'shuffleUnderwater',
  GOLDEN_ENEMY: 'shuffleGoldEnemies',
  SHOP_BOMBBAG: 'extraShopItem',
  RANDOM_BOTTLE_CONTENT: 'randomBottleContents',
  TRAPS: 'trapsEnabled',
  YES_SWORD_PROG: 'progressiveSword',
  YES_BOW_PROG: 'progressiveBow',
  YES_BOOM_PROG: 'progressiveBoomerang',
  YES_SHIELD_PROG: 'progressiveShield',
  YES_SCROLL_PROG: 'progressiveScroll',
  GORON_ALT_PRICES: 'goronJPPrices',
}

const _NUM = {
  SWORD_SETTING: ['pedSwords', v => parseInt(v) || 0],
  ELEMENT_SETTING: ['pedElements', v => parseInt(v) || 0],
  CUCCO_SETTING: ['cuccoRounds', v => { const m = v.match(/\d+$/); return m ? +m[0] : 0 }],
  GORON_SETTING: ['goronSets', v => { const m = v.match(/\d+$/); return m ? +m[0] : 0 }],
  GOLD1MULTIPLIER: ['cloudKinstoneMultiplier', v => v === 'GOLD1MAX' ? 9 : Math.max(1, +v || 1)],
  GOLD2MULTIPLIER: ['swampKinstoneMultiplier', v => v === 'GOLD2MAX' ? 3 : Math.max(1, +v || 1)],
}

const _WARP = [
  ['DWS_BLUEWARP', 'DWS_REDWARP', 'warpDWS'],
  ['COF_BLUEWARP', 'COF_REDWARP', 'warpCoF'],
  ['FOW_BLUEWARP', 'FOW_REDWARP', 'warpFoW'],
  ['TOD_BLUEWARP', 'TOD_REDWARP', 'warpToD'],
  ['POW_BLUEWARP', 'POW_REDWARP', 'warpPoW'],
  ['DHC_BLUEWARP', 'DHC_REDWARP', 'warpDHC'],
]

const _TRICK = {
  BLOWDUST_SETTING: ['bomb_dust', new Set(['GUSTBOMBS'])],
  MUSHROOM_SETTING: ['mushroom', new Set(['YESMUSH'])],
  ARROWBREAK_SETTING: ['arrows_break', new Set(['YESLIGHTS'])],
  BOBOMBS_SETTING: ['bobomb_walls', new Set(['YESBOBOMBS'])],
  LIKELIKE_SETTING: ['likelike_swordless', new Set(['YESLIKELIKE'])],
  GUARDSKIP_SETTING: ['boots_guards', new Set(['YESGUARDSKIP'])],
  CRENELBEAM_SETTING: ['beam_crenel_switch', new Set(['YESBEAM'])],
  DTBEETLE_SETTING: ['downthrust_beetle', new Set(['YESTHRUST'])],
  DARKROOMS_SETTING: ['dark_rooms', new Set(['YESDARK'])],
  EXTENDCAPE_SETTING: ['cape_extensions', new Set(['YESEXTENSION'])],
  LAKEMINISH_SETTING: ['lake_minish', new Set(['YESLAKEMINISH'])],
  CABINSWIM_SETTING: ['cabin_swim', new Set(['YESCABIN'])],
  CLOUDSKILL_SETTING: ['sharks_swordless', new Set(['YESCLOUDSKILL'])],
  POWJUMP_SETTING: ['pow_nocane', new Set(['YESPOWJUMP'])],
  POWPOTOOL_SETTING: ['pot_puzzle', new Set(['YESPOWOOL'])],
  DHCCANON_SETTING: ['dhc_cannons', new Set(['YESDHCCANON'])],
  DHCJOSTLE_SETTING: ['dhc_clones', new Set(['YESDHCJOSTLE'])],
  DHCSWITCHES_SETTING: ['dhc_spin', new Set(['YESDHCSWITCHES'])],
  FOWPOT_SETTING: ['fow_pot', new Set(['YESFOWPOT'])],
}

/**
 * Apply a preset's settings object to the settingsStore.
 * @param {Object} presetSettings  - preset.settings from presets.json
 * @param {Object} store           - useSettingsStore() instance
 */
export function applyPreset(presetSettings, store) {
  const s = presetSettings

  for (const [k, [field, map]] of Object.entries(_ENUM)) {
    if (s[k] != null && map[s[k]] != null) store[field] = map[s[k]]
  }

  for (const [k, field] of Object.entries(_BOOL)) {
    if (s[k] != null) store[field] = Boolean(s[k])
  }

  for (const [k, [field, fn]] of Object.entries(_NUM)) {
    if (s[k] != null) store[field] = fn(String(s[k]))
  }

  for (const [bk, rk, field] of _WARP) {
    if (s[bk] != null || s[rk] != null) {
      store[field] = (s[bk] ? 1 : 0) + (s[rk] ? 2 : 0)
    }
  }

  const nextTricks = new Set(store.tricks)
  for (const [k, [trick, enabled]] of Object.entries(_TRICK)) {
    if (s[k] != null) {
      if (enabled.has(s[k])) nextTricks.add(trick)
      else nextTricks.delete(trick)
    }
  }
  store.tricks = nextTricks
}
