// AUTO-GENERATED by scripts/gen_rules.py — DO NOT EDIT
// Source: SubModule/TMC-APWorld/tmc/rules.py

import {
  always, never, has, hasAny, hasAll, and, or,
  canPay, canSplit, hasMaxHealth, canActivatePedestal,
  hasSword, hasShield, hasMirrorShield,
  hasBow, hasLightArrows, hasBoomerang, hasMagicBoomerang,
  hasBombWeapon, hasBombWeaponBoss, hasGustWeapon, hasLanternWeapon,
  hasWeapon, hasWeaponBoss, hasWeaponScissor, hasWeaponWizzrobe,
  canSpin, canBeam, canHitDistance, canPassTrees,
  blowDust, mushroom, arrowBreak, likelike, darkRoom, capeExtend,
  lakeMinish, cabinSwim, fowPot, powJump, downthrust, sharkKill,
  accessTownLeft, hasBottle, accessTownFountain,
  accessLonLonRight, accessMinishWoodsTopLeft, completeBookQuest,
  smithCrest, crenelCrest, fallsCrest, cloudsCrest, swampCrest, minishCrest,
  cloudsAllCanFuse, cloudsHasFusion,
  swampsAllCanFuse, swampsHasFusion,
  fallsCanFuse, fallsHasFusion,
  dwsKey, cofKey, fowKey, todKey, rcKey, powKey, dhcKey,
} from './rules.js'

export const REGION_RULES = {
  MENU: {
    SOUTH_FIELD: always
  },
  SOUTH_FIELD: {
    HYRULE_TOWN: always,
    EASTERN_HILLS: smithCrest,
    SOUTH_PUDDLE: or(canPassTrees, hasAny("Roc's Cape", "Flippers")),
    LAKE_HYLIA_NORTH: has("Ocarina"),
    BELARI: minishCrest,
    CASTOR_WILDS: swampCrest,
    WIND_TRIBE: cloudsCrest,
    UPPER_FALLS: fallsCrest,
    MELARI: crenelCrest
  },
  SOUTH_PUDDLE: {
    SOUTH_FIELD: or(canPassTrees, hasAny("Roc's Cape", "Flippers"))
  },
  HYRULE_TOWN: {
    NORTH_FIELD: always,
    SOUTH_FIELD: always,
    LONLON: has("Bomb Bag"),
    TRILBY_HIGHLANDS: or(canSpin, and(has("Pegasus Boots"), (i,s)=>s.hasTrick("boots_guards")))
  },
  NORTH_FIELD: {
    CASTLE_EXTERIOR: always,
    HYRULE_TOWN: always,
    LONLON: canPassTrees,
    TRILBY_HIGHLANDS: hasAny("Flippers", "Roc's Cape"),
    FALLS_ENTRANCE: has("Bomb Bag"),
    ROYAL_VALLEY: and(canSplit(3, true), or(capeExtend, has("Bomb Bag")))
  },
  CASTLE_EXTERIOR: {
    NORTH_FIELD: always,
    SANCTUARY: always,
    DUNGEON_DHC_ENTRANCE: (i,s)=>s.dhcAccess==='open'
  },
  LONLON: {
    HYRULE_TOWN: has("Bomb Bag"),
    NORTH_FIELD: canPassTrees,
    EASTERN_HILLS: has("Bomb Bag"),
    MINISH_WOODS: always,
    LOWER_FALLS: has("Cane of Pacci"),
    LAKE_HYLIA_NORTH: has("LonLon Key")
  },
  EASTERN_HILLS: {
    LONLON: has("Bomb Bag"),
    BELARI: has("Bomb Bag"),
    SOUTH_FIELD: canPassTrees
  },
  LAKE_HYLIA_NORTH: {
    LONLON: always,
    LAKE_HYLIA_SOUTH: capeExtend,
    DUNGEON_TOD_ENTRANCE: capeExtend
  },
  MINISH_WOODS: {
    LONLON: always,
    LAKE_HYLIA_SOUTH: and(accessMinishWoodsTopLeft, has("Mole Mitts")),
    LAKE_HYLIA_NORTH: has("Roc's Cape"),
    DUNGEON_DWS_ENTRANCE: hasAny("Flippers", "Jabber Nut"),
    BELARI: hasAny("Bomb Bag", "Clear DWS")
  },
  BELARI: {
    MINISH_WOODS: always,
    EASTERN_HILLS: has("Bomb Bag")
  },
  WESTERN_WOODS: {
    SOUTH_PUDDLE: always,
    CASTOR_WILDS: hasAny("Pegasus Boots", "Roc's Cape"),
    TRILBY_HIGHLANDS: always
  },
  TRILBY_HIGHLANDS: {
    HYRULE_TOWN: always,
    NORTH_FIELD: or(hasAny("Roc's Cape", "Flippers"), and(has("Cane of Pacci"), hasSword)),
    WESTERN_WOODS: canSplit(2, true),
    CRENEL_BASE: hasBottle
  },
  CRENEL_BASE: {
    TRILBY_HIGHLANDS: always,
    CRENEL: or(has("Grip Ring"), and(and(has("Bomb Bag"), blowDust), hasBottle))
  },
  CRENEL: {
    CRENEL_BASE: has("Grip Ring"),
    MELARI: or(and(mushroom, has("Cane of Pacci")), and(and(has("Grip Ring"), or(hasAny("Gust Jar", "Roc's Cape"), arrowBreak)), or(or(or(hasBow, hasBoomerang), has("Bomb Bag")), or(has("Roc's Cape"), canBeam))))
  },
  MELARI: {
    CRENEL: always,
    DUNGEON_COF_ENTRANCE: always
  },
  CASTOR_WILDS: {
    WESTERN_WOODS: or(hasAny("Pegasus Boots", "Roc's Cape"), hasBow),
    WIND_RUINS: and(swampsHasFusion, and(hasAny("Roc's Cape", "Pegasus Boots"), or(or(swampCrest, hasBow), has("Flippers"))))
  },
  WIND_RUINS: {
    DUNGEON_FOW_ENTRANCE: and(hasSword, hasWeapon)
  },
  ROYAL_VALLEY: {
    NORTH_FIELD: always,
    TRILBY_HIGHLANDS: always,
    GRAVEYARD: and(hasAll("Graveyard Key", "Pegasus Boots"), darkRoom)
  },
  GRAVEYARD: {
    DUNGEON_RC: canSplit(3)
  },
  DUNGEON_RC: {
    DUNGEON_RC_CLEAR: and(and(hasWeapon, has("Small Key (RC)", 3)), has("Lantern"))
  },
  FALLS_ENTRANCE: {
    MIDDLE_FALLS: and(fallsHasFusion, darkRoom)
  },
  MIDDLE_FALLS: {
    FALLS_ENTRANCE: has("Flippers"),
    UPPER_FALLS: has("Grip Ring")
  },
  UPPER_FALLS: {
    MIDDLE_FALLS: has("Grip Ring"),
    CLOUDS: has("Grip Ring")
  },
  CLOUDS: {
    UPPER_FALLS: has("Grip Ring"),
    WIND_TRIBE: and(cloudsHasFusion, hasAny("Mole Mitts", "Roc's Cape"))
  },
  WIND_TRIBE: {
    CLOUDS: always,
    DUNGEON_POW_ENTRANCE: always
  },
  DUNGEON_DWS_ENTRANCE: {
    DUNGEON_DWS_BARREL: or(and(has("Small Key (DWS)", 4), (i,s)=>(s.warpDWS===1 || s.warpDWS===3)), and(has("Small Key (DWS)"), (i,s)=>(s.warpDWS===0 || s.warpDWS===2))),
    DUNGEON_DWS_BLUE_WARP: (i,s)=>(s.warpDWS===1 || s.warpDWS===3),
    DUNGEON_DWS_RED_WARP: (i,s)=>(s.warpDWS===2 || s.warpDWS===3),
    DUNGEON_DWS_CLEAR: and(hasAll("Big Key (DWS)", "Gust Jar"), hasWeaponBoss)
  },
  DUNGEON_DWS_BLUE_WARP: {
    DUNGEON_DWS_BACK_HALF: always
  },
  DUNGEON_DWS_BARREL: {
    DUNGEON_DWS_MULLDOZER: has("Small Key (DWS)", 4),
    DUNGEON_DWS_BACK_HALF: (i,s) => !((i,s)=>(s.warpDWS===0 || s.warpDWS===2))(i,s) || (or(dwsKey(2), has("Gust Jar")))(i,s),
    DUNGEON_DWS_RED_WARP: and(has("Small Key (DWS)", 4), has("Gust Jar"))
  },
  DUNGEON_DWS_BACK_HALF: {
    DUNGEON_DWS_BLUE_WARP: blowDust,
    DUNGEON_DWS_BARREL: always
  },
  DUNGEON_DWS_MULLDOZER: {
    DUNGEON_DWS_BACK_HALF: always
  },
  DUNGEON_COF_ENTRANCE: {
    DUNGEON_COF_MAIN: and(and(or(has("Bomb Bag"), and(or(hasSword, has("Gust Jar")), (i,s)=>s.hasTrick("bobomb_walls"))), hasWeapon), or(or(hasShield, hasAny("Cane of Pacci", "Bomb Bag")), and(downthrust, (i,s)=>s.hasTrick("downthrust_beetle")))),
    DUNGEON_COF_BLUE_WARP: (i,s)=>(s.warpCoF===1 || s.warpCoF===3),
    DUNGEON_COF_LAVA_BASEMENT: (i,s)=>(s.warpCoF===2 || s.warpCoF===3)
  },
  DUNGEON_COF_MAIN: {
    DUNGEON_COF_MINECART: and(or(and(has("Small Key (CoF)", 2), (i,s)=>(s.warpCoF===1 || s.warpCoF===3)), and(has("Small Key (CoF)"), (i,s)=>(s.warpCoF===0 || s.warpCoF===2))), hasSword)
  },
  DUNGEON_COF_MINECART: {
    DUNGEON_COF_BLUE_WARP: and(hasWeapon, hasAny("Cane of Pacci", "Roc's Cape"))
  },
  DUNGEON_COF_BLUE_WARP: {
    DUNGEON_COF_MINECART: has("Cane of Pacci"),
    DUNGEON_COF_LAVA_BASEMENT: and(and(hasSword, has("Small Key (CoF)", 2)), has("Cane of Pacci"))
  },
  DUNGEON_COF_LAVA_BASEMENT: {
    DUNGEON_COF_CLEAR: and(and(hasSword, hasWeaponBoss), hasAll("Cane of Pacci", "Big Key (CoF)"))
  },
  DUNGEON_FOW_ENTRANCE: {
    DUNGEON_FOW_EYEGORE: hasBow,
    DUNGEON_FOW_BLUE_WARP: or(and(hasWeaponBoss, (i,s)=>(s.warpFoW===1 || s.warpFoW===3)), (i,s)=>(s.warpFoW===0 || s.warpFoW===2)),
    DUNGEON_FOW_CLEAR: and(hasAll("Mole Mitts", "Big Key (FoW)"), hasBow, hasWeaponBoss)
  },
  DUNGEON_FOW_EYEGORE: {
    DUNGEON_FOW_BLUE_WARP: fowKey(4)
  },
  DUNGEON_FOW_BLUE_WARP: {
    DUNGEON_FOW_EYEGORE: always
  },
  DUNGEON_TOD_ENTRANCE: {
    DUNGEON_TOD_LEFT_BASEMENT: and(hasWeaponScissor, (i,s)=>(s.warpToD===1 || s.warpToD===3)),
    DUNGEON_TOD_WEST_SWITCH_LEDGE: and(hasAll("Bomb Bag", "Lantern"), hasWeaponBoss, (i,s)=>(s.warpToD===2 || s.warpToD===3)),
    DUNGEON_TOD_MAIN: has("Big Key (ToD)")
  },
  DUNGEON_TOD_WEST_SWITCH_LEDGE: {
    DUNGEON_TOD_MAIN: always,
    DUNGEON_TOD_WEST_SWITCH: canSplit(2)
  },
  DUNGEON_TOD_LEFT_BASEMENT: {
    DUNGEON_TOD_MAIN: always,
    DUNGEON_TOD_DARK_MAZE_END: has("Roc's Cape"),
    DUNGEON_TOD_EAST_SWITCH: canSplit(2)
  },
  DUNGEON_TOD_MAIN: {
    DUNGEON_TOD_LEFT_BASEMENT: and(todKey(4), hasAll("Flippers", "Gust Jar")),
    DUNGEON_TOD_DARK_MAZE_END: and(has("Lantern"), hasWeaponScissor, todKey(4)),
    DUNGEON_TOD_CLEAR: and(or(hasShield, hasSword), hasAll("Droplets West Switch", "Droplets East Switch", "Lantern"))
  },
  DUNGEON_TOD_DARK_MAZE_END: {
    DUNGEON_TOD_LEFT_BASEMENT: has("Roc's Cape"),
    DUNGEON_TOD_WEST_SWITCH_LEDGE: and(canSplit(2), hasAll("Lantern", "Bomb Bag"), capeExtend)
  },
  DUNGEON_POW_ENTRANCE: {
    DUNGEON_POW_BLUE_WARP: and(hasWeaponBoss, (i,s)=>(s.warpPoW===1 || s.warpPoW===3)),
    DUNGEON_POW_RED_WARP: (i,s)=>(s.warpPoW===2 || s.warpPoW===3),
    DUNGEON_POW_OUT_1F: and(canSplit(3), or(canHitDistance, hasAny("Roc's Cape", "Gust Jar")))
  },
  DUNGEON_POW_OUT_1F: {
    DUNGEON_POW_OUT_2F: powJump
  },
  DUNGEON_POW_OUT_2F: {
    DUNGEON_POW_OUT_3F: and(canSplit(3), has("Roc's Cape"))
  },
  DUNGEON_POW_OUT_3F: {
    DUNGEON_POW_OUT_4F: and(or(and(powKey(4), (i,s)=>s.warpPoW!==0), and(powKey(1), (i,s)=>s.warpPoW===0)), has("Roc's Cape"))
  },
  DUNGEON_POW_OUT_4F: {
    DUNGEON_POW_OUT_5F: has("Roc's Cape")
  },
  DUNGEON_POW_OUT_5F: {
    DUNGEON_POW_BLUE_WARP: and(has("Big Key (PoW)"), hasWeaponBoss)
  },
  DUNGEON_POW_BLUE_WARP: {
    DUNGEON_POW_IN_1F: darkRoom
  },
  DUNGEON_POW_IN_1F: {
    DUNGEON_POW_IN_2F: always
  },
  DUNGEON_POW_IN_2F: {
    DUNGEON_POW_IN_1F: darkRoom,
    DUNGEON_POW_IN_3F: and(or(and(powKey(6), (i,s)=>(s.warpPoW===2 || s.warpPoW===3)), (i,s)=>(s.warpPoW===0 || s.warpPoW===1)), has("Roc's Cape"))
  },
  DUNGEON_POW_IN_3F: {
    DUNGEON_POW_IN_2F: always,
    DUNGEON_POW_IN_3F_SWITCH: and(hasSword, hasBoomerang, hasBow, hasAny("Gust Jar", "Bomb Bag")),
    DUNGEON_POW_IN_4F: hasWeapon
  },
  DUNGEON_POW_IN_4F: {
    DUNGEON_POW_IN_3F: always,
    DUNGEON_POW_RED_WARP: and(has("Roc's Cape"), canHitDistance)
  },
  DUNGEON_POW_RED_WARP: {
    DUNGEON_POW_IN_3F: has("Bomb Bag"),
    DUNGEON_POW_IN_4F: hasAll("Bomb Bag", "Roc's Cape"),
    DUNGEON_POW_IN_5F: and(powKey(5), has("Bomb Bag"))
  },
  DUNGEON_POW_IN_5F: {
    DUNGEON_POW_IN_3F: always,
    DUNGEON_POW_IN_4F_END: powKey(6)
  },
  DUNGEON_POW_IN_4F_END: {
    DUNGEON_POW_IN_5F_END: has("Roc's Cape"),
    DUNGEON_POW_CLEAR: and(has("Roc's Cape"), has("Big Key (PoW)"), canSplit(3))
  },
  SANCTUARY: {
    CASTLE_EXTERIOR: always,
    STAINED_GLASS: canActivatePedestal
  },
  STAINED_GLASS: {
    VAATI_FIGHT: and(hasAll("Gust Jar", "Cane of Pacci"), darkRoom, hasBow, canSplit(4), (i,s)=>s.dhcAccess==='closed'),
    DUNGEON_DHC_B1_WEST: (i,s)=>s.dhcAccess!=='closed'
  },
  DUNGEON_DHC_B1_WEST: {
    SANCTUARY: always,
    DUNGEON_DHC_B2: has("Bomb Bag"),
    DUNGEON_DHC_ENTRANCE: always
  },
  DUNGEON_DHC_B2: {
    DUNGEON_DHC_B1_WEST: always
  },
  DUNGEON_DHC_ENTRANCE: {
    DUNGEON_DHC_B1_WEST: always,
    CASTLE_EXTERIOR: always,
    DUNGEON_DHC_BLUE_WARP: and(hasWeaponBoss, (i,s)=>(s.warpDHC===1 || s.warpDHC===3)),
    DUNGEON_DHC_RED_WARP: and(hasWeapon, (i,s)=>(s.warpDHC===2 || s.warpDHC===3)),
    DUNGEON_DHC_B1_EAST: and(or(and(dhcKey(5), (i,s)=>s.warpDHC!==0), and(dhcKey(1), (i,s)=>s.warpDHC===0)), (i,s) => (hasSword(i,s) && hasBombWeapon(i,s)) || s.hasTrick('dhc_cannons') || canSplit(4)(i,s), has("Bomb Bag"))
  },
  DUNGEON_DHC_B1_EAST: {
    DUNGEON_DHC_1F: hasWeaponBoss
  },
  DUNGEON_DHC_1F: {
    DUNGEON_DHC_OUTSIDE: always
  },
  DUNGEON_DHC_OUTSIDE: {
    DUNGEON_DHC_RED_WARP: and(canSplit(4), (i,s) => hasBow(i,s) || hasBoomerang(i,s) || canBeam(i,s), hasWeapon)
  },
  DUNGEON_DHC_RED_WARP: {
    DUNGEON_DHC_BLUE_WARP: and(has("Roc's Cape"), (i,s) => hasBow(i,s) || hasBoomerang(i,s) || canBeam(i,s), hasAny("Bomb Bag", "Gust Jar"), hasWeaponBoss),
    VAATI_FIGHT: and(hasAll("Big Key (DHC)", "Gust Jar", "Cane of Pacci"), hasWeaponBoss, canSplit(4), hasBow, darkRoom)
  },
  FUSIONS: {}
}

export const LOCATION_RULES = {
  "South Field Minish Size Water Hole Item": and(canPassTrees, hasAll("Pegasus Boots", "Flippers")),
  "South Field Tingle NPC": hasAll("Cane of Pacci", "Tingle Trophy"),
  "Town Shop 80 Item": canPay(80),
  "Town Shop 300 Item": canPay(300),
  "Town Shop 600 Item": canPay(600),
  "Town Shop 600 Item 2": canPay(600),
  "Town Shop Behind Counter Item": accessTownLeft,
  "Town Shop Attic Chest": accessTownLeft,
  "Town Bakery Attic Chest": accessTownLeft,
  "Town Inn Backdoor HP": accessTownLeft,
  "Town Inn Ledge Chest": has("Lantern"),
  "Town Goron Merchant 1 Left": canPay(300),
  "Town Goron Merchant 1 Middle": canPay(200),
  "Town Goron Merchant 1 Right": canPay(50),
  "Town Goron Merchant 2 Left": canPay(300),
  "Town Goron Merchant 2 Middle": canPay(300),
  "Town Goron Merchant 2 Right": canPay(300),
  "Town Goron Merchant 3 Left": canPay(400),
  "Town Goron Merchant 3 Middle": canPay(300),
  "Town Goron Merchant 3 Right": canPay(300),
  "Town Goron Merchant 4 Left": canPay(500),
  "Town Goron Merchant 4 Middle": canPay(400),
  "Town Goron Merchant 4 Right": canPay(400),
  "Town Goron Merchant 5 Left": canPay(600),
  "Town Goron Merchant 5 Middle": canPay(500),
  "Town Goron Merchant 5 Right": canPay(500),
  "Town Dojo NPC Sword": hasSword,
  "Town Dojo NPC Green Sword": or(has("White Sword"), has("Progressive Sword", 2)),
  "Town Dojo NPC Boots + Sword": and(hasSword, has("Pegasus Boots")),
  "Town Dojo NPC Cape + Sword": and(hasSword, has("Roc's Cape")),
  "Town Well Top Chest": has("Bomb Bag"),
  "Town School Roof Chest": has("Cane of Pacci"),
  "Town School Path Fusion Chest": has("Cane of Pacci"),
  "Town School Path Left Chest": and(has("Cane of Pacci"), canSplit(4)),
  "Town School Path Middle Chest": and(has("Cane of Pacci"), canSplit(4)),
  "Town School Path Right Chest": and(has("Cane of Pacci"), canSplit(4)),
  "Town School Path HP": and(has("Cane of Pacci"), canSplit(4)),
  "Town Digging Left Chest": has("Mole Mitts"),
  "Town Digging Top Chest": has("Mole Mitts"),
  "Town Digging Right Chest": has("Mole Mitts"),
  "Town Well Left Chest": has("Mole Mitts"),
  "Town Bell HP": has("Roc's Cape"),
  "Town Waterfall Fusion Chest": has("Flippers"),
  "Town Carlov NPC": accessTownLeft,
  "Town Well Bottom Chest": hasAny("Roc's Cape", "Flippers"),
  "Town Cuccos Lv 10": hasAny("Roc's Cape", "Flippers"),
  "Town Jullieta Item": and(accessTownLeft, hasBottle),
  "Town Simulation Chest": and(hasSword, canPay(10)),
  "Town Shoe Shop NPC": has("Wakeup Mushroom"),
  "Town Music House Left Chest": has("Carlov Medal"),
  "Town Music House Middle Chest": has("Carlov Medal"),
  "Town Music House Right Chest": has("Carlov Medal"),
  "Town Music House HP": has("Carlov Medal"),
  "Town Well Pillar Chest": and(has("Mole Mitts"), hasAny("Roc's Cape", "Flippers"), canSplit(3, true)),
  "Town Dr Left Attic Item": and(accessTownLeft, hasAll("Power Bracelets", "Gust Jar"), canSplit(2)),
  "Town Fountain Big Chest": and(hasWeapon, accessTownFountain, has("Cane of Pacci")),
  "Town Fountain Small Chest": and(accessTownFountain, hasAny("Flippers", "Roc's Cape")),
  "Town Fountain HP": and(accessTownFountain, has("Roc's Cape")),
  "Town Library Yellow Minish NPC": completeBookQuest,
  "Town Under Library Frozen Chest": hasAll("Ocarina", "Cane of Pacci", "Flippers", "Lantern"),
  "Town Under Library Big Chest": and(or(and(completeBookQuest, has("Grip Ring"), hasAny("Gust Jar", "Roc's Cape")), hasAll("Ocarina", "Cane of Pacci", "Flippers")), hasWeaponScissor),
  "Town Under Library Underwater": hasAll("Ocarina", "Cane of Pacci", "Flippers"),
  "North Field Dig Spot": has("Mole Mitts"),
  "North Field HP": or(has("Bomb Bag"), capeExtend),
  "North Field Waterfall Fusion Dojo NPC": and(has("Flippers"), hasSword),
  "Castle Moat Left Chest": has("Flippers"),
  "Castle Moat Right Chest": has("Flippers"),
  "Castle Golden Rope": hasSword,
  "Castle Dojo NPC": and(has("Lantern"), hasSword),
  "Castle Right Fountain Fusion Minish Hole Chest": has("Pegasus Boots"),
  "Castle Left Fountain Fusion Minish Hole Chest": has("Pegasus Boots"),
  "Hills Golden Rope": hasSword,
  "Hills Bomb Cave Chest": has("Bomb Bag"),
  "Minish Great Fairy NPC": has("Cane of Pacci"),
  "Hills Farm Dig Cave Item": has("Mole Mitts"),
  "Lon Lon Puddle Fusion Big Chest": accessLonLonRight,
  "Lon Lon Cave Chest": and(accessLonLonRight, canSplit(2, true)),
  "Lon Lon Cave Secret Chest": and(accessLonLonRight, canSplit(2, true), hasAll("Bomb Bag", "Lantern")),
  "Lon Lon Path Fusion Chest": and(accessLonLonRight, has("Pegasus Boots")),
  "Lon Lon Path HP": and(accessLonLonRight, has("Pegasus Boots")),
  "Lon Lon Dig Spot": and(accessLonLonRight, hasAny("Cane of Pacci", "Roc's Cape"), has("Mole Mitts")),
  "Lon Lon North Minish Crack Chest": and(accessLonLonRight, hasAny("Cane of Pacci", "Roc's Cape")),
  "Lon Lon Goron Cave Fusion Small Chest": accessMinishWoodsTopLeft,
  "Lon Lon Goron Cave Fusion Big Chest": accessMinishWoodsTopLeft,
  "Falls Lower Waterfall Fusion Dojo NPC": and(has("Flippers"), hasSword),
  "Falls Lower Rock Item1": hasAny("Flippers", "Roc's Cape"),
  "Falls Lower Rock Item2": hasAny("Flippers", "Roc's Cape"),
  "Falls Lower Rock Item3": hasAny("Flippers", "Roc's Cape"),
  "Falls Lower Dig Cave Left Chest": and(hasAny("Flippers", "Roc's Cape"), has("Mole Mitts")),
  "Falls Lower Dig Cave Right Chest": and(hasAny("Flippers", "Roc's Cape"), has("Mole Mitts")),
  "Hylia Sunken HP": has("Flippers"),
  "Hylia Dog NPC": has("Dog Food"),
  "Hylia Small Island HP": has("Roc's Cape"),
  "Hylia Cape Cave Top Right": hasAll("Mole Mitts", "Roc's Cape"),
  "Hylia Cape Cave Bottom Left": hasAll("Mole Mitts", "Roc's Cape"),
  "Hylia Cape Cave Top Left": hasAll("Mole Mitts", "Roc's Cape"),
  "Hylia Cape Cave Top Middle": hasAll("Mole Mitts", "Roc's Cape"),
  "Hylia Cape Cave Right": hasAll("Mole Mitts", "Roc's Cape"),
  "Hylia Cape Cave Bottom Right": hasAll("Mole Mitts", "Roc's Cape"),
  "Hylia Cape Cave Bottom Middle": hasAll("Mole Mitts", "Roc's Cape"),
  "Hylia Cape Cave Lon Lon HP": hasAll("Mole Mitts", "Roc's Cape"),
  "Hylia Beanstalk Fusion Left Chest": hasAll("Mole Mitts", "Roc's Cape"),
  "Hylia Beanstalk Fusion HP": hasAll("Mole Mitts", "Roc's Cape"),
  "Hylia Beanstalk Fusion Right Chest": hasAll("Mole Mitts", "Roc's Cape"),
  "Hylia Middle Island Fusion Dig Cave Chest": and(has("Mole Mitts"), capeExtend),
  "Hylia Bottom HP": capeExtend,
  "Hylia Dojo HP": capeExtend,
  "Hylia Dojo NPC": and(capeExtend, hasMaxHealth(10), hasSword),
  "Hylia Crack Fusion Librari NPC": and(has("Ocarina"), hasAny("Flippers", "Roc's Cape")),
  "Hylia North Minish Hole Chest": and(lakeMinish, has("Flippers")),
  "Hylia South Minish Hole Chest": and(lakeMinish, has("Flippers")),
  "Hylia Cabin Path Fusion Chest": and(lakeMinish, cabinSwim),
  "Hylia Mayor Cabin Item": and(lakeMinish, cabinSwim, has("Power Bracelets")),
  "Minish Woods Golden Octo": and(accessMinishWoodsTopLeft, hasSword),
  "Minish Woods Witch Hut Item": and(accessMinishWoodsTopLeft, canPay(60)),
  "Witch Digging Cave Chest": and(accessMinishWoodsTopLeft, has("Mole Mitts")),
  "Minish Woods North Fusion Chest": accessMinishWoodsTopLeft,
  "Minish Woods Top HP": accessMinishWoodsTopLeft,
  "Minish Woods Like Like Digging Cave Left Chest": and(has("Mole Mitts"), likelike),
  "Minish Woods Like Like Digging Cave Right Chest": and(has("Mole Mitts"), likelike),
  "Minish Woods Flipper Hole Middle Chest": has("Flippers"),
  "Minish Woods Flipper Hole Right Chest": has("Flippers"),
  "Minish Woods Flipper Hole Left Chest": has("Flippers"),
  "Minish Woods Flipper Hole HP": has("Flippers"),
  "Trilby Dig Cave Left Chest": has("Mole Mitts"),
  "Trilby Dig Cave Right Chest": has("Mole Mitts"),
  "Trilby Dig Cave Water Fusion Chest": and(has("Mole Mitts"), hasAny("Roc's Cape", "Flippers")),
  "Trilby Scrub NPC": and(hasShield, has("Bomb Bag"), canPay(20)),
  "Trilby Bomb Cave Chest": has("Bomb Bag"),
  "Western Woods Top Dig 1": has("Mole Mitts"),
  "Western Woods Top Dig 2": has("Mole Mitts"),
  "Western Woods Top Dig 3": has("Mole Mitts"),
  "Western Woods Top Dig 4": has("Mole Mitts"),
  "Western Woods Top Dig 5": has("Mole Mitts"),
  "Western Woods Top Dig 6": has("Mole Mitts"),
  "Western Woods Percy Fusion Moblin": has("Lantern"),
  "Western Woods Percy Fusion Percy": has("Lantern"),
  "Western Woods Bottom Dig 1": has("Mole Mitts"),
  "Western Woods Bottom Dig 2": has("Mole Mitts"),
  "Western Woods Golden Octo": hasSword,
  "Crenel Base Fairy Cave Item Left": has("Bomb Bag"),
  "Crenel Base Fairy Cave Item Middle": has("Bomb Bag"),
  "Crenel Base Fairy Cave Item Right": has("Bomb Bag"),
  "Crenel Base Green Water Fusion Chest": has("Bomb Bag"),
  "Crenel Base West Fusion Chest": hasAny("Bomb Bag", "Roc's Cape"),
  "Crenel Base Water Cave Left Chest": has("Bomb Bag"),
  "Crenel Base Water Cave Right Chest": has("Bomb Bag"),
  "Crenel Base Water Cave HP": has("Bomb Bag"),
  "Crenel Base Minish Vine Hole Chest": and(hasAny("Bomb Bag", "Roc's Cape"), blowDust),
  "Crenel Base Minish Crack Chest": and(hasAny("Bomb Bag", "Roc's Cape"), blowDust),
  "Crenel Vine Top Golden Tektite": hasSword,
  "Crenel Bridge Cave Chest": has("Bomb Bag"),
  "Crenel Fairy Cave HP": has("Bomb Bag"),
  "Crenel Below CoF Golden Tektite": and(hasSword, mushroom),
  "Crenel Scrub NPC": and(has("Bomb Bag"), hasShield, canPay(40), mushroom),
  "Crenel Dojo Left Chest": and(has("Grip Ring"), canSplit(2, true)),
  "Crenel Dojo Right Chest": and(has("Grip Ring"), canSplit(2, true)),
  "Crenel Dojo HP": and(has("Grip Ring"), canSplit(2, true)),
  "Crenel Dojo NPC": and(has("Grip Ring"), canSplit(2, true)),
  "Crenel Great Fairy NPC": hasAll("Grip Ring", "Bomb Bag"),
  "Crenel Climb Fusion Chest": hasAll("Grip Ring", "Bomb Bag"),
  "Crenel Dig Cave HP": hasAll("Grip Ring", "Mole Mitts"),
  "Crenel Beanstalk Fusion HP": has("Grip Ring"),
  "Crenel Beanstalk Fusion Item 1": has("Grip Ring"),
  "Crenel Beanstalk Fusion Item 2": has("Grip Ring"),
  "Crenel Beanstalk Fusion Item 3": has("Grip Ring"),
  "Crenel Beanstalk Fusion Item 4": has("Grip Ring"),
  "Crenel Beanstalk Fusion Item 5": has("Grip Ring"),
  "Crenel Beanstalk Fusion Item 6": has("Grip Ring"),
  "Crenel Beanstalk Fusion Item 7": has("Grip Ring"),
  "Crenel Beanstalk Fusion Item 8": has("Grip Ring"),
  "Crenel Rain Path Fusion Chest": has("Grip Ring"),
  "Melari Mines: Left Dig": has("Mole Mitts"),
  "Melari Mines: Top Middle Dig": has("Mole Mitts"),
  "Melari Mines: Top Left Dig": has("Mole Mitts"),
  "Melari Mines: Top Right Dig": has("Mole Mitts"),
  "Melari Mines: Bottom Right Dig": has("Mole Mitts"),
  "Melari Mines: Bottom Middle Dig": has("Mole Mitts"),
  "Melari Mines: Bottom Left Dig": has("Mole Mitts"),
  "Melari Mines: Center Dig": has("Mole Mitts"),
  "Fused with West Statue": and(swampsAllCanFuse, and(hasAny("Roc's Cape", "Pegasus Boots"), or(or(swampCrest, hasBow), has("Flippers")))),
  "Fused with Middle Statue": and(swampsAllCanFuse, and(hasAny("Roc's Cape", "Pegasus Boots"), or(or(swampCrest, hasBow), has("Flippers")))),
  "Fused with East Statue": and(swampsAllCanFuse, and(hasAny("Roc's Cape", "Pegasus Boots"), or(or(swampCrest, hasBow), has("Flippers")))),
  "Swamp Center Cave Darknut Chest": hasWeaponBoss,
  "Swamp Center Chest": hasBow,
  "Swamp Golden Rope": hasSword,
  "Swamp Near Waterfall Cave HP": and(hasBow, hasAny("Roc's Cape", "Flippers")),
  "Swamp Waterfall Fusion Dojo NPC": and(hasSword, hasBow, has("Flippers")),
  "Swamp North Cave Chest": hasBow,
  "Swamp Digging Cave Left Chest": has("Mole Mitts"),
  "Swamp Digging Cave Right Chest": has("Mole Mitts"),
  "Swamp Underwater Top": has("Flippers"),
  "Swamp Underwater Middle": has("Flippers"),
  "Swamp Underwater Bottom": has("Flippers"),
  "Swamp South Cave Chest": or(hasAny("Roc's Cape", "Flippers"), hasBow),
  "Swamp Dojo HP": or(has("Roc's Cape"), hasBow, hasAll("Pegasus Boots", "Flippers"), and(swampCrest, has("Pegasus Boots"))),
  "Swamp Dojo NPC": and(or(has("Roc's Cape"), hasBow, hasAll("Pegasus Boots", "Flippers"), and(swampCrest, has("Pegasus Boots"))), hasSword),
  "Swamp Minish Fusion North Crack Chest": or(hasAny("Pegasus Boots", "Roc's Cape"), hasBow),
  "Swamp Minish Mulldozer Big Chest": and(or(hasAny("Pegasus Boots", "Roc's Cape"), hasBow), hasAny("Flippers", "Gust Jar"), hasWeapon),
  "Swamp Minish Fusion North West Crack Chest": and(or(hasAny("Pegasus Boots", "Roc's Cape"), hasBow), hasAny("Flippers", "Gust Jar")),
  "Swamp Minish Fusion West Crack Chest": or(hasAny("Pegasus Boots", "Roc's Cape"), hasBow),
  "Swamp Minish Fusion Vine Crack Chest": or(hasAny("Pegasus Boots", "Roc's Cape"), hasBow),
  "Swamp Minish Fusion Water Hole Chest": and(has("Flippers"), or(hasAny("Pegasus Boots", "Roc's Cape"), hasBow)),
  "Swamp Minish Fusion Water Hole HP": and(has("Flippers"), or(hasAny("Pegasus Boots", "Roc's Cape"), hasBow)),
  "Ruins Bomb Cave Chest": has("Bomb Bag"),
  "Ruins Pillars Fusion Chest": hasSword,
  "Ruins Bean Stalk Fusion Big Chest": and(hasSword, hasWeapon),
  "Ruins Crack Fusion Chest": and(hasSword, hasWeapon),
  "Ruins Minish Cave HP": and(hasSword, hasWeapon),
  "Ruins Armos Kill Left Chest": and(hasSword, hasWeapon),
  "Ruins Armos Kill Right Chest": and(hasSword, hasWeapon),
  "Ruins Golden Octo": and(hasSword, hasWeapon),
  "Ruins Near Dungeon Fusion Chest": and(hasSword, hasWeapon),
  "Valley Great Fairy NPC": has("Bomb Bag"),
  "Valley Lost Woods Chest": darkRoom,
  "Valley Dampe NPC": darkRoom,
  "Valley Graveyard Left Grave HP": canSplit(3, true),
  "Crypt Gibdo Left Item": or(has("Lantern"), hasWeapon),
  "Crypt Gibdo Right Item": or(has("Lantern"), hasWeapon),
  "Crypt Left Item": and(canSplit(3), has("Small Key (RC)")),
  "Crypt Right Item": and(canSplit(3), has("Small Key (RC)")),
  "Fused with Veil Falls Door": fallsCanFuse,
  "Falls Entrance HP": capeExtend,
  "Falls Water Dig Cave Fusion HP": and(has("Mole Mitts"), capeExtend),
  "Falls Water Dig Cave Fusion Chest": and(has("Mole Mitts"), capeExtend),
  "Falls 1st Cave Chest": has("Bomb Bag"),
  "Falls Cliff Chest": and(has("Bomb Bag"), canSplit(3, true)),
  "Falls South Dig Spot": has("Mole Mitts"),
  "Falls Golden Tektite": hasSword,
  "Falls North Dig Spot": has("Mole Mitts"),
  "Falls Waterfall Fusion HP": has("Flippers"),
  "Falls Rupee Cave Underwater Top Left": has("Flippers"),
  "Falls Rupee Cave Underwater Top Right": has("Flippers"),
  "Falls Rupee Cave Underwater Middle Left": has("Flippers"),
  "Falls Rupee Cave Underwater Middle Right": has("Flippers"),
  "Falls Rupee Cave Underwater Bottom Left": has("Flippers"),
  "Falls Rupee Cave Underwater Bottom Right": has("Flippers"),
  "Falls Top Cave Bomb Wall Chest": has("Bomb Bag"),
  "Falls Biggoron Item": or(hasMirrorShield, hasShield),
  "Fused with Top Right Cloud": cloudsAllCanFuse,
  "Fused with Bottom Left Cloud": cloudsAllCanFuse,
  "Fused with Top Left Cloud": cloudsAllCanFuse,
  "Fused with Middle Cloud": cloudsAllCanFuse,
  "Fused with Bottom Right Cloud": cloudsAllCanFuse,
  "Clouds North East Dig Spot": has("Mole Mitts"),
  "Clouds North Shark Kill": and(hasAny("Roc's Cape", "Mole Mitts"), sharkKill),
  "Clouds North West Left Chest": has("Mole Mitts"),
  "Clouds North West Right Chest": has("Mole Mitts"),
  "Clouds North West Dig Spot": has("Mole Mitts"),
  "Clouds North West Bottom Chest": hasAny("Mole Mitts", "Roc's Cape"),
  "Clouds South Left Chest": has("Mole Mitts"),
  "Clouds South Dig Spot": has("Mole Mitts"),
  "Clouds South Middle Chest": hasAny("Mole Mitts", "Roc's Cape"),
  "Clouds South Middle Dig Spot": has("Mole Mitts"),
  "Clouds South Shark Kill": and(hasAny("Roc's Cape", "Mole Mitts"), sharkKill),
  "Clouds South Right Chest": hasAny("Mole Mitts", "Roc's Cape"),
  "Clouds South Right Dig Spot": has("Mole Mitts"),
  "Clouds South East Bottom Dig Spot": has("Mole Mitts"),
  "Clouds South East Top Dig Spot": has("Mole Mitts"),
  "Wind Tribe 2F Gregal NPC 1": has("Gust Jar"),
  "Wind Tribe 2F Gregal NPC 2": has("Gust Jar"),
  "Deepwood 2F Chest": hasAny("Lantern", "Gust Jar"),
  "Deepwood 1F Barrel Room Chest": blowDust,
  "Deepwood 1F East Mulldozer Fight Item": hasWeapon,
  "Deepwood 1F North East Chest": blowDust,
  "Deepwood B1 Switch Room Chest": hasAny("Gust Jar", "Roc's Cape"),
  "Deepwood 1F Blue Warp Left Chest": blowDust,
  "Deepwood 1F Blue Warp Right Chest": blowDust,
  "Deepwood 1F Madderpillar Big Chest": and(hasWeaponBoss, or(has("Small Key (DWS)", 4), has("Lantern"))),
  "Deepwood 1F Madderpillar HP": or(and(has("Small Key (DWS)", 4), has("Gust Jar")), has("Lantern")),
  "CoF B1 Hazy Room Big Chest": hasWeaponWizzrobe,
  "CoF B1 Hazy Room Small Chest": hasWeaponWizzrobe,
  "CoF B1 Rollobite Chest": hasWeaponWizzrobe,
  "CoF B1 Rollobite Pillar Chest": hasWeaponWizzrobe,
  "CoF B1 Spikey Chus Pillar Chest": has("Cane of Pacci"),
  "CoF B1 HP": has("Bomb Bag"),
  "CoF B1 Spikey Chus Big Chest": hasWeapon,
  "CoF B2 Pre Lava North Chest": has("Cane of Pacci"),
  "CoF B2 Pre Lava South Chest": has("Cane of Pacci"),
  "CoF B2 Lava Room Blade Chest": hasAny("Cane of Pacci", "Roc's Cape"),
  "CoF B2 Lava Room Right Chest": hasAny("Cane of Pacci", "Roc's Cape"),
  "CoF B2 Lava Room Left Chest": hasAny("Cane of Pacci", "Roc's Cape"),
  "CoF B2 Lava Room Big Chest": hasAny("Cane of Pacci", "Roc's Cape"),
  "Fortress Entrance 1F Left Chest": has("Mole Mitts"),
  "Fortress Entrance 1F Left Wizzrobe Chest": and(has("Mole Mitts"), hasWeaponWizzrobe),
  "Fortress Entrance 1F Right Item": has("Mole Mitts"),
  "Fortress Left 2F Dig Chest": and(hasBow, hasWeapon, has("Mole Mitts")),
  "Fortress Left 2F Item 1": and(hasBow, hasWeapon),
  "Fortress Left 2F Item 2": and(hasBow, hasWeapon),
  "Fortress Left 2F Item 3": and(hasBow, hasWeapon),
  "Fortress Left 2F Item 4": and(hasBow, hasWeapon),
  "Fortress Left 2F Item 5": and(hasBow, hasWeapon),
  "Fortress Left 2F Item 6": and(hasBow, hasWeapon),
  "Fortress Left 2F Item 7": and(hasBow, hasWeapon),
  "Fortress Left 3F Switch Chest": and(hasBow, hasWeapon, has("Mole Mitts")),
  "Fortress Left 3F Eyegore Big Chest": and(hasBow, hasWeapon),
  "Fortress Left 3F Item Drop": and(hasBow, hasWeapon, or(has("Roc's Cape"), canSplit(2))),
  "Fortress Middle 2F Statue Chest": has("Mole Mitts"),
  "Fortress Right 2F Dig Chest": has("Mole Mitts"),
  "Fortress Right 3F Dig Chest": has("Mole Mitts"),
  "Fortress Right 3F Item Drop": canSplit(2),
  "Fortress Entrance 1F Right HP": canSplit(2),
  "Fortress Back Right Dig Room Bottom Pot": or(fowPot, and(has("Small Key (FoW)", 3), has("Mole Mitts"), or(hasBow, or(and(hasWeaponBoss, (i,s)=>(s.warpFoW===1 || s.warpFoW===3)), (i,s)=>(s.warpFoW===0 || s.warpFoW===2))))),
  "Fortress Back Left Big Chest": has("Bomb Bag"),
  "Fortress Back Left Small Chest": hasAll("Bomb Bag", "Mole Mitts"),
  "Fortress Back Right Statue Item Drop": and(has("Small Key (FoW)", 2), canSplit(2)),
  "Fortress Back Right Minish Item Drop": and(has("Small Key (FoW)", 3), hasWeapon, has("Mole Mitts")),
  "Fortress Back Right Dig Room Top Pot": and(has("Small Key (FoW)", 3), has("Mole Mitts")),
  "Fortress Back Right Big Chest": and(has("Small Key (FoW)", 4), has("Mole Mitts")),
  "Droplets Entrance B2 West Iceblock": todKey(1),
  "Droplets Left Path B1 Waterfall Underwater 1": has("Flippers"),
  "Droplets Left Path B1 Waterfall Underwater 2": has("Flippers"),
  "Droplets Left Path B1 Waterfall Underwater 3": has("Flippers"),
  "Droplets Left Path B1 Waterfall Underwater 4": has("Flippers"),
  "Droplets Left Path B1 Waterfall Underwater 5": has("Flippers"),
  "Droplets Left Path B1 Waterfall Underwater 6": has("Flippers"),
  "Droplets Left Path B2 Waterfall Underwater 1": and(has("Flippers"), hasAny("Gust Jar", "Roc's Cape")),
  "Droplets Left Path B2 Waterfall Underwater 2": and(has("Flippers"), hasAny("Gust Jar", "Roc's Cape")),
  "Droplets Left Path B2 Waterfall Underwater 3": and(has("Flippers"), hasAny("Gust Jar", "Roc's Cape")),
  "Droplets Left Path B2 Waterfall Underwater 4": and(has("Flippers"), hasAny("Gust Jar", "Roc's Cape")),
  "Droplets Left Path B2 Waterfall Underwater 5": and(has("Flippers"), hasAny("Gust Jar", "Roc's Cape")),
  "Droplets Left Path B2 Waterfall Underwater 6": and(has("Flippers"), hasAny("Gust Jar", "Roc's Cape")),
  "Droplets Left Path B2 Underwater Pot": and(has("Flippers"), or(and(hasWeaponScissor, (i,s)=>(s.warpToD===1 || s.warpToD===3)), hasAny("Gust Jar", "Roc's Cape"))),
  "Droplets Right Path B1 1st Chest": (i,s) => has("Lantern")(i) || has("Droplets East Switch")(i),
  "Droplets Right Path B1 2nd Chest": (i,s) => has("Lantern")(i) || has("Droplets East Switch")(i),
  "Droplets Right Path B1 Pot": (i,s) => has("Lantern")(i) || has("Droplets East Switch")(i),
  "Droplets Right Path B3 Frozen Chest": (i,s) => has("Lantern")(i) || has("Droplets East Switch")(i),
  "Droplets Right Path B1 Blu Chu Big Chest": and((i,s) => has("Lantern")(i) || has("Droplets East Switch")(i), has("Small Key (ToD)", 4), has("Gust Jar"), hasWeaponBoss),
  "Droplets Right Path B2 Frozen Chest": has("Lantern"),
  "Droplets Right Path B2 Dark Maze Bottom Chest": and(hasWeaponScissor, has("Lantern")),
  "Droplets Right Path B2 Mulldozers Item Drop": and(hasWeaponScissor, hasWeapon, hasAll("Lantern", "Bomb Bag")),
  "Droplets Right Path B2 Dark Maze Top Right Chest": and(hasWeaponScissor, has("Lantern")),
  "Droplets Right Path B2 Dark Maze Top Left Chest": and(hasWeaponScissor, has("Lantern")),
  "Droplets Left Path B2 Ice Madderpillar Big Chest": and(hasWeaponBoss, has("Gust Jar")),
  "Droplets Left Path B2 Ice Plain Frozen Chest": and(has("Lantern"), hasAny("Flippers", "Gust Jar", "Roc's Cape")),
  "Droplets Left Path B2 Ice Plain Chest": hasAny("Flippers", "Gust Jar", "Roc's Cape"),
  "Droplets Left Path B2 Lilypad Corner Frozen Chest": hasAll("Gust Jar", "Lantern"),
  "Palace 1st Half 1F Grate Chest": has("Roc's Cape"),
  "Palace 1st Half 1F Wizzrobe Big Chest": and(hasWeaponWizzrobe, or(hasBoomerang, hasAny("Roc's Cape", "Bomb Bag"))),
  "Palace 1st Half 3F Pot Puzzle Item Drop": and(has("Cane of Pacci"), (i,s) => (has("Power Bracelets")(i) && powKey(1)(i)) || (powKey(6)(i) && s.hasTrick('pot_puzzle'))),
  "Palace 1st Half 5F Ball And Chain Soldiers Item Drop": hasWeapon,
  "Palace 1st Half 5F Fan Loop Chest": and(has("Roc's Cape"), has("Small Key (PoW)", 5), hasWeapon),
  "Palace 1st Half 5F Big Chest": has("Small Key (PoW)", 6),
  "Palace 2nd Half 2F Many Rollers Chest": and(canSplit(3), has("Roc's Cape")),
  "Palace 2nd Half 2F Twin Wizzrobes Chest": hasWeaponWizzrobe,
  "Palace 2nd Half 3F Fire Wizzrobes Big Chest": hasWeaponWizzrobe,
  "Palace 2nd Half 4F HP": has("Roc's Cape"),
  "Palace 2nd Half 4F Switch Hit Chest": and(canHitDistance, and(has("Roc's Cape"), (i,s)=>(s.warpPoW===2 || s.warpPoW===3))),
  "Pedestal Requirement Reward": canActivatePedestal,
  "Sanctuary Pedestal Item1": hasAll("Earth Element","Fire Element","Water Element","Wind Element"),
  "Sanctuary Pedestal Item2": hasAll("Earth Element","Fire Element","Water Element","Wind Element"),
  "Sanctuary Pedestal Item3": hasAll("Earth Element","Fire Element","Water Element","Wind Element"),
  "DHC B2 King": canSplit(4),
  "DHC 1F Blade Chest": and((i,s) => (hasSword(i,s) && hasBombWeapon(i,s)) || s.hasTrick('dhc_cannons') || canSplit(4)(i,s), (i,s) => canSplit(2,true)(i,s) || s.hasTrick('dhc_clones') || canSplit(4)(i,s)),
  "DHC 3F North West Chest": and(hasWeaponBoss, hasBow),
  "DHC 3F North East Chest": and(hasWeaponBoss, has("Lantern")),
  "DHC 3F South West Chest": and(hasWeaponBoss, (i,s) => s.warpDHC!==0 || hasAny("Bomb Bag","Roc's Cape")(i)),
  "DHC 3F South East Chest": and(hasWeaponBoss, (i,s) => s.warpDHC!==0 || hasAny("Bomb Bag","Roc's Cape")(i), (i,s) => canSpin(i,s) || s.hasTrick('dhc_spin') || canSplit(4)(i,s)),
  "DHC 2F Blue Warp Big Chest": and(has("Small Key (DHC)", 5), canSplit(4))
}
